apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 65.0.0  # Latest stable version
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # Prometheus Configuration
    prometheus:
      enabled: true
      prometheusSpec:
        replicas: 1
        retention: 15d
        retentionSize: "18GB"

        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi

        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi

        # Service Monitor Selector - will auto-discover ServiceMonitors
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}

        # Add Istio scrape configs
        additionalScrapeConfigs:
          - job_name: 'istiod'
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - istio-system
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                action: keep
                regex: istiod;http-monitoring

          - job_name: 'envoy-stats'
            metrics_path: /stats/prometheus
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_container_port_name]
                action: keep
                regex: '.*-envoy-prom'
              - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                action: replace
                regex: ([^:]+)(?::\d+)?;(\d+)
                replacement: $1:15020
                target_label: __address__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: pod_name

    # Grafana Configuration (included in stack)
    grafana:
      enabled: true
      adminPassword: "admin"  # CHANGE THIS IN PRODUCTION!

      service:
        type: ClusterIP
        port: 80

      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

      # Pre-configured dashboards for Istio
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'istio'
              orgId: 1
              folder: 'Istio'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/istio

    # AlertManager (optional)
    alertmanager:
      enabled: true
      alertmanagerSpec:
        replicas: 1
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi

    # Node Exporter
    nodeExporter:
      enabled: true

    # Kube State Metrics
    kubeStateMetrics:
      enabled: true

    # Default Service Monitors
    defaultRules:
      create: true

    # Prometheus Operator
    prometheusOperator:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi