# Staging environment values
global:
  namespace: financial-news-staging
  environment: staging
  imageRegistry: your-registry
  imagePullPolicy: Always

commonLabels:
  environment: staging
  managed-by: helm

alertSignal:
  replicaCount: 1

  image:
    tag: staging

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "250m"

  autoscaling:
    minReplicas: 1
    maxReplicas: 2

marketImpact:
  replicaCount: 1

  image:
    tag: staging

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  autoscaling:
    minReplicas: 1
    maxReplicas: 2

newsIngestion:
  replicaCount: 1

  image:
    tag: staging

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  autoscaling:
    minReplicas: 1
    maxReplicas: 2

nlpProcessing:
  replicaCount: 1

  image:
    tag: staging

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  autoscaling:
    minReplicas: 1
    maxReplicas: 3