apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: financial-news
type: Opaque
stringData:
  host: "postgres.curiyq4aismn.us-east-1.rds.amazonaws.com"
  port: "5432"
  username: "postgres_Financ"
  password: "Yahya_zakaria123456789"