apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: financial-news-services
  namespace: financial-news
spec:
  host: "*.financial-news.svc.cluster.local"
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        http2MaxRequests: 100
        maxRequestsPerConnection: 2
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      minHealthPercent: 50
  exportTo:
    - "."