apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: istio-system
  dependsOn:
    - name: istiod
      namespace: flux-system
  chart:
    spec:
      chart: gateway
      version: 1.24.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    remediation:
      retries: 3
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  values:
    # ✅ CORRECTED: Istio Gateway 1.24.x uses different schema
    # The chart now expects configuration at the root level

    # Basic metadata
    name: istio-ingressgateway

    # Labels for pod selector
    labels:
      istio: ingressgateway
      app: istio-ingressgateway

    # Service configuration
    service:
      type: LoadBalancer  # Change to NodePort for local k8s
      ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          port: 80
          protocol: TCP
          targetPort: 8080
        - name: https
          port: 443
          protocol: TCP
          targetPort: 8443
        - name: grpc
          port: 50051
          protocol: TCP
          targetPort: 50051

      # Uncomment for AWS EKS
      # annotations:
      #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      #   service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

    # Deployment configuration
    replicaCount: 2

    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi

    # Autoscaling
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80

    # Service account
    serviceAccount:
      create: true
      name: istio-ingressgateway