apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: istio-system
  dependsOn:
    - name: istiod
      namespace: flux-system
  chart:
    spec:
      chart: gateway
      version: 1.24.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    remediation:
      retries: 3
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  # ✅ MINIMAL CONFIG: Let Istio use smart defaults
  # The gateway chart in 1.24.x has a complex schema with _internal_defaults_do_not_set
  # Best practice is to keep it simple and only override what's necessary
  values:
    # Override labels to match your existing VirtualServices
    labels:
      istio: ingressgateway
      app: istio-ingressgateway

    # Service type - use LoadBalancer to get external IP
    service:
      type: LoadBalancer  # Change to NodePort for Minikube/local clusters
      # Ports will use sensible defaults (80, 443, 15021)
      # Uncomment for AWS EKS:
      # annotations:
      #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"