apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: istio-system
  dependsOn:
    - name: istiod
      namespace: flux-system
  chart:
    spec:
      chart: gateway
      version: 1.24.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    remediation:
      retries: 3
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  # ✅ SOLUTION: Use NO custom values for Istio Gateway 1.24.x
  # The chart will create a gateway with sensible defaults:
  # - Deployment named: istio-ingressgateway
  # - Service type: LoadBalancer
  # - Ports: 15021 (status), 80 (http), 443 (https)
  # - Labels: istio=ingressgateway
  #
  # If you need customization, do it via Kubernetes patches AFTER deployment
  # or downgrade to Istio 1.23.x which has a more flexible schema