apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: market-impact
  namespace: financial-news
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: market-impact

  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: market-impact

  service:
    port: 8082
    targetPort: 8082
    portName: http
    portDiscovery: true
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL

  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10

    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m

      - name: request-duration
        thresholdRange:
          max: 1000
        interval: 1m

      - name: error-rate
        templateRef:
          name: error-rate
          namespace: istio-system
        thresholdRange:
          max: 1
        interval: 1m

    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: http://flagger-loadtester.financial-news/
        timeout: 10s  # ← Much shorter!
        metadata:
          type: bash
          cmd: "curl -sf http://market-impact-canary.financial-news:8082/market-impact/actuator/health | grep -q '\"status\":\"UP\"'"