apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: nlp-processing
  namespace: financial-news
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nlp-processing

  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: nlp-processing

  service:
    # ✅ FIXED: Define both ports as an array
    ports:
      - name: grpc
        port: 50052
        targetPort: 50052
      - name: http
        port: 8080
        targetPort: 8080
    portDiscovery: true
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL

  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10

    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m

      - name: request-duration
        thresholdRange:
          max: 2000
        interval: 1m

      - name: error-rate
        templateRef:
          name: error-rate
          namespace: istio-system
        thresholdRange:
          max: 1
        interval: 1m

      - name: cpu-usage
        templateRef:
          name: cpu-usage
          namespace: istio-system
        thresholdRange:
          max: 80
        interval: 1m

    webhooks:
      # ✅ FIXED: Simpler health check without grep
      - name: acceptance-test
        type: pre-rollout
        url: http://flagger-loadtester.financial-news/
        timeout: 30s
        metadata:
          type: bash
          cmd: "curl -sf http://nlp-processing-canary.financial-news:8080/health"

      # ✅ FIXED: Use HTTP health endpoint for load test
      - name: load-test
        type: rollout
        url: http://flagger-loadtester.financial-news/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://nlp-processing-canary.financial-news:8080/health"