apiVersion: v1
kind: Service
metadata:
  name: nlp-processing
  namespace: financial-news
  labels:
    app: nlp-processing
spec:
  type: ClusterIP
  ports:
    - port: 50052
      targetPort: 50052
      protocol: TCP
      name: grpc
  selector:
    app: nlp-processing