apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-configs
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/production/infrastructure/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  # ⚠️ CRITICAL: Wait for Istio to be fully ready
  dependsOn:
    - name: flux-system  # Wait for main infrastructure

  # Health checks - ensure Istio CRDs are installed
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istiod
      namespace: istio-system

  timeout: 5m0s
  retryInterval: 2m0s