# clusters/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml              # Create namespace first
  - infrastructure/istio        # Then Istio
  - infrastructure/monitoring   # Then monitoring (Prometheus)
  - infrastructure/flagger      # Then Flagger (installs CRDs)
  - infrastructure/secrets      # Then secrets
  - infrastructure/configs      # Then configs
#  - infrastructure/ingress
  - helmrelease.yaml           # Deploy application
  - canaries-kustomization.yaml # Canaries deployed after Flagger is ready