# clusters/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
   - namespace.yaml
   - infrastructure/istio
   - infrastructure/monitoring
   - infrastructure/flagger
   - infrastructure/nginx-ingress  # ADD THIS LINE
   - infrastructure/secrets
   - infrastructure/configs
   - helmrelease.yaml
   - canaries-kustomization.yaml