apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - infrastructure/istio
  - infrastructure/monitoring
  - infrastructure/flagger
  - infrastructure/nginx-ingress
  - infrastructure/secrets
  - infrastructure/configs
  - helmrelease.yaml
  - ingress-kustomization.yaml  # ← Reference the Flux Kustomization file directly
  - canaries-kustomization.yaml