# clusters/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml              # Create namespace first
  - infrastructure/istio        # Then Istio
  - infrastructure/monitoring   # Then monitoring (Prometheus)
  - infrastructure/flagger      # Then Flagger
  - infrastructure/secrets      # Then secrets
  - infrastructure/configs      # Then configs
  - helmrelease.yaml           # Deploy application
  - canaries                   # Finally setup canaries