apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml        # Create namespace first
  - infrastructure/istio    # Then Istio
  - infrastructure/secrets  # Then secrets
  - infrastructure/configs  # Then configs
  - helmrelease.yaml
  - infrastructure/monitoring  # ✅ Add this line
# Finally the application