apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-ingestion
  namespace: financial-news
  labels:
    app: news-ingestion
    component: ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-ingestion
  template:
    metadata:
      labels:
        app: news-ingestion
        component: ingestion
    spec:
      containers:
        - name: news-ingestion
          image: yahyazakaria123/market-impact-analysis-system-news-ingestion-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
              name: http
              protocol: TCP
            - containerPort: 4002
              name: grpc
              protocol: TCP
          env:
            - name: SERVER_HTTP_PORT
              value: "4001"
            - name: SERVER_GRPC_PORT
              value: "4002"
            - name: SERVER_ENVIRONMENT
              value: "production"

            # Database Configuration
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database

            # Redis Configuration
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: port
                  optional: true
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
                  optional: true

            # NewsAPI Configuration
            - name: NEWSAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: newsapi-key
                  optional: true

            # NLP Service Configuration
            - name: NLP_PROCESSING_HOST
              value: "nlp-processing.financial-news.svc.cluster.local"
            - name: NLP_PROCESSING_PORT
              value: "50052"

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

          livenessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3