apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-signal
  namespace: financial-news
  labels:
    app: alert-signal
    component: alerts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alert-signal
  template:
    metadata:
      labels:
        app: alert-signal
        component: alerts
    spec:
      containers:
        - name: alert-signal
          image: yahyazakaria123/market-impact-analysis-system-alert-signal-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
            - containerPort: 9095
              name: grpc
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: GRPC_SERVER_PORT
              value: "9095"

            # Database Configuration
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database

            # Redis Configuration
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: port
                  optional: true
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
                  optional: true

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3