apiVersion: v1
kind: Service
metadata:
  name: alert-signal
  namespace: financial-news
  labels:
    app: alert-signal
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
    - port: 9095
      targetPort: 9095
      protocol: TCP
      name: grpc
  selector:
    app: alert-signal