apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: financial-news-staging

resources:
  - ../news-ingestion
  - ../nlp-processing
  - ../market-impact
  - ../alert-signal
  - namespace.yaml

# Strategic patches for staging
patches:
  # Staging: smaller replicas and resources
  - target:
      kind: Deployment
      name: news-ingestion
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: your-registry/news-ingestion:staging
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"

  - target:
      kind: Deployment
      name: nlp-processing
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: your-registry/nlp-processing:staging
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "250m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"

  - target:
      kind: Deployment
      name: market-impact
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: your-registry/market-impact:staging
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"

  - target:
      kind: Deployment
      name: alert-signal
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: your-registry/alert-signal:staging
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "50m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "250m"

  # HPA patches for staging
  - target:
      kind: HorizontalPodAutoscaler
      name: news-ingestion
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 2
      - op: replace
        path: /spec/minReplicas
        value: 1

  - target:
      kind: HorizontalPodAutoscaler
      name: nlp-processing
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 3
      - op: replace
        path: /spec/minReplicas
        value: 1

  - target:
      kind: HorizontalPodAutoscaler
      name: market-impact
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 2
      - op: replace
        path: /spec/minReplicas
        value: 1

  - target:
      kind: HorizontalPodAutoscaler
      name: alert-signal
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 2
      - op: replace
        path: /spec/minReplicas
        value: 1
