apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-processing
  namespace: financial-news
  labels:
    app: nlp-processing
    component: nlp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nlp-processing
  template:
    metadata:
      labels:
        app: nlp-processing
        component: nlp
    spec:
      containers:
        - name: nlp-processing
          image: your-registry/nlp-processing:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50052
              name: grpc
              protocol: TCP
          env:
            - name: SERVER_GRPC_PORT
              value: "50052"
            - name: SERVER_ENVIRONMENT
              value: "production"

            # Database Configuration
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database

            # Redis Configuration
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: port
                  optional: true
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
                  optional: true

            # News Ingestion Service
            - name: NEWS_INGESTION_HOST
              value: "news-ingestion.financial-news.svc.cluster.local"
            - name: NEWS_INGESTION_PORT
              value: "4002"

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"

          livenessProbe:
            exec:
              command: ["/usr/local/bin/grpc_health_probe", "-addr=:50052"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command: ["/usr/local/bin/grpc_health_probe", "-addr=:50052"]
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3