# infrastructure/istio/istiod.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 30m
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: 1.24.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    pilot:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi