apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: istio-system
  dependsOn:
    - name: istiod
      namespace: flux-system
    - name: kube-prometheus-stack
      namespace: flux-system
  chart:
    spec:
      chart: kiali-server
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    deployment:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # ✅ FIXED: Add /prometheus route prefix since Prometheus is configured with routePrefix
    external_services:
      prometheus:
        url: "http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/prometheus"
        # Note: Added /prometheus at the end because your prometheus.yaml has:
        # routePrefix: /prometheus

      grafana:
        enabled: true
        in_cluster_url: "http://monitoring-kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
        url: "http://monitoring-kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"

    auth:
      strategy: "anonymous"

    server:
      web_root: "/kiali"
      web_port: 20001

    istio_namespace: "istio-system"

    kiali_feature_flags:
      istio_injection_action: true
      istio_upgrade_action: false
      ui_defaults:
        metrics_per_refresh: "1m"
        namespaces: []
        refresh_interval: "60s"