apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: istio-system
  dependsOn:
    - name: istiod
      namespace: flux-system
    - name: kube-prometheus-stack  # ✅ Update name
      namespace: flux-system
  chart:
    spec:
      chart: kiali-server
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Deployment configuration
    deployment:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # External services configuration
    # In kiali-production.yaml or kiali.yaml
    external_services:
      prometheus:
        url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"  # ✅ Updated
      grafana:
        enabled: true
        in_cluster_url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"  # ✅ Updated
        url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"

    # Auth configuration
    auth:
      strategy: "anonymous"  # Change to "token" or "openid" for production

    # Server configuration
    server:
      web_root: "/kiali"
      web_port: 20001

    # Istio configuration
    istio_namespace: "istio-system"

    # Kiali features
    kiali_feature_flags:
      istio_injection_action: true
      istio_upgrade_action: false
      ui_defaults:
        metrics_per_refresh: "1m"
        namespaces: []
        refresh_interval: "60s"