apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - kiali-helmrepository.yaml  # Add this
  - istio-base.yaml
  - istiod.yaml
  - kiali.yaml
  - kiali-ingress.yaml
#  - kiali-production.yaml # production overrides