# clusters/production/infrastructure/flagger/flagger.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: istio-system
  dependsOn:
    - name: istiod
      namespace: flux-system
    - name: kube-prometheus-stack
      namespace: flux-system
  chart:
    spec:
      chart: flagger
      version: 1.38.0
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  install:
    remediation:
      retries: 3
    crds: CreateReplace  # ✅ ADD THIS
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace  # ✅ ADD THIS
  values:
    metricsServer: "http://kube-prometheus-stack-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
    meshProvider: istio  # ✅ Already correct
    logLevel: info
    resources:
      limits:
        memory: "512Mi"
        cpu: "1000m"
      requests:
        memory: "32Mi"
        cpu: "10m"
    prometheus:
      install: false
    threadiness: 10
    namespace: ""
    includeNamespaces:
      - financial-news